name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: carbide-pilot-330923
  GAR_LOCATION: us-central1 # e.g. us-central1
  SERVICE: my-app
  REGION: us-central1

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write' # Required for OIDC token
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/865336692250/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'cloud-run-deployer-sa@carbide-pilot-330923.iam.gserviceaccount.com'

      # Setup gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      # Build and push container image
      - name: Build and Push Container
        run: |-
          gcloud auth configure-docker ${GAR_LOCATION}-docker.pkg.dev
          gcloud builds submit --tag ${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${SERVICE}/${SERVICE}:${{ github.sha }}

      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy ${{ env.SERVICE }} \
            --region ${{ env.REGION }} \
            --image ${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${SERVICE}/${SERVICE}:${{ github.sha }} \
            --platform managed \
            --allow-unauthenticated